# Generated by Django 4.0 on 2024-06-06 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
    ]
